#!/usr/bin/python3
import sys
import argparse
import find_tumor

parser = argparse.ArgumentParser()
parser.add_argument("--inputfile",type=str, action="store")
args = parser.parse_args()

sys.stdout.write(find_tumor.find_tumor(args.inputfile))